services:
    postgres:
        container_name: rinha_backend_postgres
        image: postgres:15
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: rinha
        ports:
            - "5432:5432"